// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/edufriendchen/tiktok-demo/cmd/api/biz/handler"
	
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!

	root := r.Group("/douyin")

		{
			_user := root.Group("/user")
			_user.GET("/",  handler.GetUserInfo)
			_user.POST("/login",  handler.Login)
			_user.POST("/register", handler.Register)
		}
}
