// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/app/server/registry"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/kitex/pkg/utils"
	"github.com/edufriendchen/httpvlog"
	"github.com/edufriendchen/tiktok-demo/cmd/api/biz/initialize"
	"github.com/edufriendchen/tiktok-demo/cmd/api/biz/rpc"
	"github.com/edufriendchen/tiktok-demo/pkg/consts"
	"github.com/hertz-contrib/obs-opentelemetry/logging/logrus"
)

func Init() {
	rpc.Init()
	initialize.InitJWT()
	hlog.SetLogger(logrus.NewLogger())
	hlog.SetLevel(hlog.LevelInfo)
}

func main() {
	Init()
	r, _ := initialize.InitNacos()
	//tracer, cfg := tracing.NewServerTracer()
	h := server.New(
		server.WithHostPorts(consts.ApiServiceAddr),
		server.WithHandleMethodNotAllowed(true),
		server.WithRegistry(r, &registry.Info{
			ServiceName: consts.ApiServiceName,
			Addr:        utils.NewNetAddr(consts.TCP, consts.ApiServiceAddr),
			Weight:      10,
			Tags:        nil,
		}),
		//tracer,
	)
	//h.Use(tracing.ServerMiddleware(cfg))
	h.Use(httpvlog.Logger())
	register(h)
	h.Spin()
}
